name: Security Full Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  full_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # CodeQL Full Scan
      # -------------------------
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: |
            javascript-typescript
            python
          build-mode: none

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      # -------------------------
      # Bearer Full Scan
      # -------------------------
      - name: Bearer Full Scan
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: bearer-results.sarif

      - name: Upload Bearer SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bearer-results.sarif
